services:

    msc-converter:
      container_name: msc-converter
      build:
        context: "./msc-converter"
        dockerfile: Dockerfile
      networks:
        - msc-network
      ports:
        - "57840:57840"
  
    msc-exchange-rate-provider:
      container_name: msc-exchange-rate-provider
      build:
        context: "./msc-exchange-rate-provider"
        dockerfile: Dockerfile
      networks:
        - msc-network
      ports:
        - "44302:44302"
    
    msc-app:
      container_name: msc-app
      build:
        context: "./msc-app"
        dockerfile: Dockerfile
      networks:
        - msc-network
      ports:
        - 3000:3000
      environment:
        - CHOKIDAR_USEPOLLING=true
    
networks:
      msc-network:
        external: true
        